name: mpacklog
channels:
    - conda-forge
dependencies:
    - aiofiles >= 23.2.1
    - loop-rate-limiters >= 1.0.0
    - msgpack-python >= 1.0.2
    - pip >= 21.3.1
    - pip:
        - furo >= 2023.8.17
        - sphinx >= 7.2.2
        - sphinx-autodoc-typehints
        - sphinx-favicon
